spring.application.name=ecommerce-backend
server.port=${PORT:8080}
server.forward-headers-strategy=framework
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}
spring.datasource.username=${DB_USERNAME:ecommerce}
spring.datasource.password=${DB_PASSWORD:ecommerce}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.flyway.enabled=${FLYWAY_ENABLED:false}
springdoc.swagger-ui.path=/swagger-ui.html
